# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    contactmethod.methods:
        class: AppBundle\Service\ContactMethodService
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]
        scope: request
